TAGS_AND_ATTRIBUTES = (
    '_about', '_accept', '_accept_charset', '_acceptCharset', '_accessKey', '_accumulate', '_action', '_additive',
    '_align', '_alignmentBaseline', '_alink', '_allow', '_allowFullScreen', '_allowReorder', '_allowTransparency',
    '_allowPaymentRequest', '_allowUserMedia', '_alphabetic', '_alt', '_amplitude', '_archive', '_aria_autocomplete',
    '_aria_busy', '_aria_checked', '_aria_current', '_aria_disabled', '_aria_expanded', '_aria_haspopup',
    '_aria_hidden', '_aria_invalid', '_aria_modal', '_aria_multiline', '_aria_multiselectable', '_aria_orientation',
    '_aria_polite', '_aria_pressed', '_aria_readonly', '_aria_relevant', '_aria_required', '_aria_selected',
    '_aria_sort', '_ascent', '_async', '_attributeName', '_attributeType', '_autoCapitalize', '_autoComplete',
    '_autoCorrect', '_autoFocus', '_autoPlay', '_autoReverse', '_autoSave', '_axis', '_azimuth', '_background',
    '_baseFrequency', '_baseProfile', '_baselineShift', '_bbox', '_begin', '_bgcolor', '_bias', '_border', '_calcMode',
    '_capture', '_cellPadding', '_cellSpacing', '_challenge', '_char', '_charset', '_charoff', '_checked', '_class',
    '_classID', '_className', '_clear', '_clip', '_clipPathUnits', '_clipRule', '_codebase', '_codetype', '_color',
    '_colorInterpolation', '_colorInterpolationFilters', '_colorProfile', '_colorRendering', '_cols', '_colspan',
    '_compact', '_contentEditable', '_contentScriptType', '_contentStyleType', '_contextMenu', '_controls', '_coords',
    '_crossOrigin', '_cursor', '_cx', '_cy', '_d', '_datatype', '_datetime', '_decelerate', '_declare', '_decoding',
    '_default', '_defaultChecked', '_defaultValue', '_defer', '_descent', '_diffuseConstant', '_direction', '_dirname',
    '_disabled', '_display', '_divisor', '_dominantBaseline', '_download', '_draggable', '_dur', '_dx', '_dy',
    '_edgeMode', '_elevation', '_enableBackground', '_enctype', '_end', '_enterKeyHint', '_exponent',
    '_externalResourcesRequired', '_face', '_fill', '_fillOpacity', '_fillRule', '_filter', '_filterRes',
    '_filterUnits', '_floodColor', '_floodOpacity', '_focusable', '_fontFamily', '_fontSize', '_fontSizeAdjust',
    '_fontStretch', '_fontStyle', '_fontVariant', '_fontWeight', '_for', '_formAction', '_formEncType', '_formMethod',
    '_formNoValidate', '_formTarget', '_format', '_frameBorder', '_from', '_fx', '_fy', '_g1', '_g2', '_glyphName',
    '_glyphOrientationHorizontal', '_glyphOrientationVertical', '_glyphRef', '_gradientTransform', '_gradientUnits',
    '_hanging', '_headers', '_height', '_hidden', '_high', '_horizAdvX', '_horizOriginX', '_href', '_hreflang',
    '_hspace', '_htmlFor', '_http_equiv', '_httpEquiv', '_icon', '_id', '_ideographic', '_imagesizes', '_imagesrcset',
    '_in', '_in2', '_inlist', '_inputMode', '_integrity', '_intercept', '_is', '_ismap', '_itemID', '_itemProp',
    '_itemRef', '_itemScope', '_itemType', '_keyParams', '_keyPoints', '_keySplines', '_keyTimes', '_keyType', '_kind',
    '_lang', '_language', '_lengthAdjust', '_letterSpacing', '_lightingColor', '_list', '_local', '_longdesc', '_loop',
    '_low', '_manifest', '_marginHeight', '_marginWidth', '_markerEnd', '_markerHeight', '_markerMid', '_markerStart',
    '_markerUnits', '_markerWidth', '_maskContentUnits', '_maskUnits', '_mathematical', '_max', '_maxlength', '_media',
    '_mediaGroup', '_method', '_min', '_minlength', '_mode', '_multiple', '_muted', '_name', '_nohref', '_nomodule',
    '_nonce', '_noresize', '_noshade', '_novalidate', '_nowrap', '_offset', '_onabort', '_onafterprint', '_onauxclick',
    '_onbeforeprint', '_onbeforeunload', '_onblur', '_oncancel', '_oncanplay', '_oncanplaythrough', '_onchange',
    '_onclick', '_onclose', '_oncontextmenu', '_oncopy', '_oncuechange', '_oncut', '_ondblclick', '_ondrag',
    '_ondragend', '_ondragenter', '_ondragexit', '_ondragleave', '_ondragover', '_ondragstart', '_ondrop',
    '_ondurationchange', '_onemptied', '_onended', '_onerror', '_onfocus', '_onformdata', '_onhashchange', '_oninput',
    '_oninvalid', '_onkeydown', '_onkeypress', '_onkeyup', '_onlanguagechange', '_onload', '_onloadeddata',
    '_onloadedmetadata', '_onloadend', '_onloadstart', '_onmessage', '_onmessageerror', '_onmousedown', '_onmouseenter',
    '_onmouseleave', '_onmousemove', '_onmouseout', '_onmouseover', '_onmouseup', '_onoffline', '_ononline',
    '_onpagehide', '_onpageshow', '_onpaste', '_onpause', '_onplay', '_onplaying', '_onpopstate', '_onprogress',
    '_onratechange', '_onrejectionhandled', '_onreset', '_onresize', '_onscroll', '_onsecuritypolicyviolation',
    '_onseeked', '_onseeking', '_onselect', '_onslotchange', '_onstalled', '_onstorage', '_onsubmit', '_onsuspend',
    '_ontimeupdate', '_ontoggle', '_onunhandledrejection', '_onunload', '_onvolumechange', '_onwaiting', '_onwheel',
    '_opacity', '_open', '_operator', '_optimum', '_order', '_orient', '_orientation', '_origin', '_overflow',
    '_overlinePosition', '_overlineThickness', '_paintOrder', '_pathLength', '_patternContentUnits',
    '_patternTransform', '_patternUnits', '_ping', '_placeholder', '_playsInline', '_pointerEvents', '_points',
    '_pointsAtX', '_pointsAtY', '_pointsAtZ', '_poster', '_prefix', '_preload', '_preserveAlpha',
    '_preserveAspectRatio', '_primitiveUnits', '_profile', '_prompt', '_property', '_r', '_radioGroup', '_radius',
    '_readonly', '_refX', '_refY', '_rel', '_renderingIntent', '_repeatCount', '_repeatDur', '_required',
    '_requiredExtensions', '_requiredFeatures', '_resource', '_restart', '_result', '_results', '_rev', '_reversed',
    '_role', '_rotate', '_rows', '_rowspan', '_rules', '_rx', '_ry', '_sandbox', '_scale', '_scheme', '_scope',
    '_scoped', '_scrolling', '_seamless', '_security', '_seed', '_selected', '_shape', '_shapeRendering', '_size',
    '_sizes', '_slope', '_spacing', '_specularConstant', '_specularExponent', '_speed', '_spellcheck', '_spreadMethod',
    '_src', '_srcdoc', '_srclang', '_srcset', '_standby', '_start', '_startOffset', '_step', '_stopColor',
    '_stopOpacity', '_strikethroughPosition', '_strikethroughThickness', '_string', '_stroke', '_strokeDasharray',
    '_strokeDashoffset', '_strokeLinecap', '_strokeLinejoin', '_strokeMiterlimit', '_strokeOpacity', '_strokeWidth',
    '_surfaceScale', '_systemLanguage', '_tabindex', '_target', '_targetX', '_targetY', '_textAnchor',
    '_textDecoration', '_textLength', '_textRendering', '_to', '_transform', '_translate', '_type', '_typemustmatch',
    '_typeof', '_u1', '_u2', '_underlinePosition', '_underlineThickness', '_unicode', '_unicodeRange', '_unitsPerEm',
    '_unselectable', '_usemap', '_valign', '_value', '_values', '_version', '_vertAdvY', '_vertOriginX', '_vertOriginY',
    '_viewBox', '_viewTarget', '_visibility', '_vlink', '_vocab', '_vspace', '_width', '_widths', '_wmode',
    '_wordSpacing', '_wrap', '_writingMode', '_x', '_x1', '_x2', '_xChannelSelector', '_xHeight', '_xlinkActuate',
    '_xlinkArcrole', '_xlinkHref', '_xlinkRole', '_xlinkShow', '_xlinkTitle', '_xlinkType', '_xmlBase', '_xmlLang',
    '_xmlSpace', '_xmlns', '_xmlnsXlink', '_y', '_y1', '_y2', '_yChannelSelector', '_z',

    'a', 'abbr', 'acronym', 'address', 'applet', 'area', 'article', 'aside', 'audio', 'b', 'base', 'basefont', 'bdi',
    'bdo', 'bgsound', 'big', 'blink', 'blockquote', 'body', 'br', 'button', 'canvas', 'caption', 'center', 'circle',
    'cite', 'clipPath', 'code', 'col', 'colgroup', 'command', 'content', 'data', 'datalist', 'dd', 'details', 'dfn',
    'dialog', 'dir', 'div', 'dl', 'dt', 'element', 'ellipse', 'em', 'embed', 'fieldset', 'figcaption', 'figure', 'font',
    'footer', 'foreignObject', 'form', 'frame', 'frameset', 'g', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'head', 'header',
    'hgroup', 'hr', 'html', 'i', 'iframe', 'image', 'img', 'ins', 'isindex', 'kbd', 'keygen', 'label', 'legend', 'li',
    'line', 'linearGradient', 'link', 'listing', 'main', 'mark', 'marquee', 'mask', 'math', 'menu', 'menuitem', 'meta',
    'meter', 'multicol', 'nav', 'nextid', 'nobr', 'noembed', 'noframes', 'noscript', 'object', 'ol', 'optgroup',
    'option', 'output', 'p', 'param', 'path', 'pattern', 'picture', 'plaintext', 'polygon', 'polyline', 'pre',
    'progress', 'q', 'radialGradient', 'rb', 'rbc', 'rect', 'rp', 'rt', 'rtc', 'ruby', 's', 'samp', 'script', 'section',
    'select', 'shadow', 'slot', 'small', 'source', 'spacer', 'span', 'stop', 'strike', 'strong', 'style', 'sub',
    'summary', 'sup', 'svg', 'table', 'tbody', 'td', 'template', 'textarea', 'tfoot', 'th', 'thead', 'time', 'title',
    'tr', 'track', 'tspan', 'tt', 'u', 'ul', 'var', 'video', 'wbr', 'xmp'
)

OTHER = ('input_', 'any', 'text', 'name', 'contains', 'last')

from .attributes import *
from .custom import *
from .tags import *

__all__ = TAGS_AND_ATTRIBUTES + OTHER
